print('-'*35)
print('Tugas 1 SISOP Kelas-A')
print('-'*35)
print('Nama: Muhamad Haris Hartanto')
print('NPM : 21083010045')
print('-'*35)
print('notes:')
print('-'*35)
print('Halo dunia!\nIni adalah skrip Bash pertamaku di Linux')
